### Tạo Tensor cơ bản

In [2]:
import torch

a = torch.tensor(
    [[1,2,3],
     [4,5,6]],
    dtype=torch.int32
)

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


- kích thước: 2x3
- số chiều: 2
- kiểu dữ liệu: torch.int32 (số nguyên 32-bit)

### Tạo các Tensor thường dùng

In [3]:
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.6394, 0.6253, 0.2941, 0.6399],
        [0.7686, 0.3819, 0.3924, 0.7104],
        [0.2206, 0.7069, 0.3688, 0.5964]])
tensor([[ 1.1918, -1.0460,  0.1348, -0.8319],
        [-0.2305, -1.6950, -1.4112,  0.0580],
        [ 0.4068,  1.7889, -0.0441,  0.1701]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


- Sự khác nhau giữa torch.rand() và torch.randn():
| Đặc điểm| torch.rand()|torch.randn()|
|--------:|------------:|------------:|
|**Phân phối**|Phân phối đều|Phân phối chuẩn hóa|
|**Khoảng giá trị**|[0,1)|(-$\infty$,+$\infty$)|
|**Giá trị trung bình**|$\approx$ 0.5|$\approx$ 0|
|**Độ lệch chuẩn**|$\approx$ 0.289|1|
|**Ký tự nhận biết**|rand = random| randn = random normal|

- Tạo thêm một tensor 5x5 chứa toàn giá trị 10

In [5]:
x = torch.full((5,5), 10)
print(x)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### Kiểm tra thông tin Tensor

In [7]:
a = torch.zeros(2,3,4)
print("Tensor: ")
print("Shape: ", a.shape)
print("Size: ", a.size())
print("Number of dimensions: ", a.ndim)
print("Data type: ", a.dtype)
print(a)

Tensor: 
Shape:  torch.Size([2, 3, 4])
Size:  torch.Size([2, 3, 4])
Number of dimensions:  3
Data type:  torch.float32
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


- Ý nghĩa của torch.Size([2, 3, 4]): độ dày = 2, chiều cao = 3, chiều rộng = 4

### Slicing và Indexing